application: gtass-1256
version: 1
runtime: php55
api_version: 1

handlers:
- url: /
  script: /view/index.php

- url: /admin
  script: /view/adminFormTest.php

- url: /createsession
  script: /controller/adminController.php