application: gtass-1256
version: s1
runtime: php55
api_version: 1

handlers:
- url: /
  script: view/index.php

- url: /admin
  script: view/successLoginAdmin.php

- url: /adminCtrl
  script: controller/adminController.php

- url: /nomCtrl
  script: controller/nominatorController.php

- url: /addNominees
  script: view/addNomineesForm.php

- url: /addNomineesTest
  script: view/addNomineesTest.php

- url: /addNominators
  script: view/addNominatorsForm.php

- url: /GC
  script: view/gcHomeView.php

- url: /login
  script: controller/loginController.php

- url: /logout
  script: controller/loginController.php

- url: /currentSession
  script: view/currentSession.php
  
- url: /nomineeForm
  script: view/nomineeForm.php 

- url: /public
  static_dir: view/public
