application: gtass-1256
version: s1
runtime: php55
api_version: 1

handlers:
- url: /
  script: view/index.php

- url: /createSession
  script: view/createSession.php

- url: /adminCtrl
  script: controller/adminController.php

- url: /nominatorCtrl
  script: controller/nominatorController.php

- url: /nomineeCtrl
  script: controller/nomineeController.php

- url: /accountCtrl
  script: controller/accountController.php

- url: /account
  script: view/account.php

- url: /addNominees
  script: view/addNomineesForm.php

- url: /addNomineesTest
  script: view/addNomineesTest.php

- url: /addNominators
  script: view/addNominatorsForm.php

- url: /gcHome
  script: view/gcHome.php

- url: /login
  script: controller/loginController.php

- url: /logout
  script: controller/loginController.php

- url: /currentSession
  script: view/currentSession.php

- url: /allSessions
  script: view/allSessionsView.php

- url: /nomineeForm
  script: view/nomineeForm.php

- url: /nomineeReminderTask
  script: resources/scripts/nominee2dayNotificationEmail.php

- url: /nominatorHome
  script: view/nominatorHome.php

- url: /adminHome
  script: view/adminHome.php

- url: /incompleteNominations
  script: view/incompleteNominations.php

- url: /public
  static_dir: view/public
