application: gtass-1256
version: 1
runtime: php55
api_version: 1

handlers:
- url: /
  script: /view/index.php

- url: /admin
  script: /view/successLoginAdmin.php

- url: /createsession
  script: /controller/adminController.php

- url: /GC
  script: /view/gcHomeView.php

- url: /login
  script: /controller/loginController.php

- url: /logout
  script: /controller/loginController.php

